/** @typedef MediaProduct
 * @property {object} attributes
 * @property {string} attributes.title
 * @property {string} attributes.isrc
 * @property {string} attributes.duration
 * @property {string} attributes.copyright
 * @property {boolean} attributes.explicit
 * @property {number} attributes.popularity
 * @property {string[]} attributes.availability
 * @property {string[]} attributes.mediaTags
 * @property {object[]} attributes.externalLinks
 * @property {string} attributes.externalLinks.href
 * @property {object} attributes.externalLinks.meta
 * @property {string} attributes.externalLinks.meta.type
 * @property {object} relationships
 * @property {object} relationships.albums
 * @property {object[]} relationships.albums.data
 * @property {string} relationships.albums.data.id
 * @property {string} relationships.albums.data.type
 * @property {object} relationships.albums.links
 * @property {string} relationships.albums.links.self
 * @property {object} relationships.artists
 * @property {object[]} relationships.artists.data
 * @property {string} relationships.artists.data.id
 * @property {string} relationships.artists.data.type
 * @property {object} relationships.artists.links
 * @property {string} relationships.artists.links.self
 * @property {object} relationships.providers
 * @property {object} relationships.providers.links
 * @property {string} relationships.providers.links.self
 * @property {object} relationships.similarTracks
 * @property {object} relationships.similarTracks.links
 * @property {string} relationships.similarTracks.links.self
 * @property {object} relationships.radio
 * @property {object} relationships.radio.links
 * @property {string} relationships.radio.links.self
 * @property {object} links
 * @property {string} links.self
 * @property {string} id
 * @property {string} type
 */


/** @typedef Album
 * @property {object} attributes
 * @property {string} attributes.title
 * @property {string} attributes.barcodeId
 * @property {number} attributes.numberOfVolumes
 * @property {number} attributes.numberOfItems
 * @property {string} attributes.duration
 * @property {boolean} attributes.explicit
 * @property {string} attributes.releaseDate
 * @property {string} attributes.copyright
 * @property {number} attributes.popularity
 * @property {string[]} attributes.availability
 * @property {string[]} attributes.mediaTags
 * @property {object[]} attributes.imageLinks
 * @property {string} attributes.imageLinks.href
 * @property {object} attributes.imageLinks.meta
 * @property {number} attributes.imageLinks.meta.width
 * @property {number} attributes.imageLinks.meta.height
 * @property {Array<unknown>} attributes.videoLinks
 * @property {object[]} attributes.externalLinks
 * @property {string} attributes.externalLinks.href
 * @property {object} attributes.externalLinks.meta
 * @property {string} attributes.externalLinks.meta.type
 * @property {object} relationships
 * @property {object} relationships.artists
 * @property {object} relationships.artists.links
 * @property {string} relationships.artists.links.self
 * @property {object} relationships.items
 * @property {object} relationships.items.links
 * @property {string} relationships.items.links.self
 * @property {object} relationships.similarAlbums
 * @property {object} relationships.similarAlbums.links
 * @property {string} relationships.similarAlbums.links.self
 * @property {object} relationships.providers
 * @property {object} relationships.providers.links
 * @property {string} relationships.providers.links.self
 * @property {object} links
 * @property {string} links.self
 * @property {string} id
 * @property {string} type
 */

/** @typedef Artist
 * @property {object} attributes
 * @property {string} attributes.name
 * @property {number} attributes.popularity
 * @property {Array<unknown>} attributes.imageLinks
 * @property {object[]} attributes.externalLinks
 * @property {string} attributes.externalLinks.href
 * @property {object} attributes.externalLinks.meta
 * @property {string} attributes.externalLinks.meta.type
 * @property {object} relationships
 * @property {object} relationships.albums
 * @property {object} relationships.albums.links
 * @property {string} relationships.albums.links.self
 * @property {object} relationships.tracks
 * @property {object} relationships.tracks.links
 * @property {string} relationships.tracks.links.self
 * @property {object} relationships.videos
 * @property {object} relationships.videos.links
 * @property {string} relationships.videos.links.self
 * @property {object} relationships.similarArtists
 * @property {object} relationships.similarArtists.links
 * @property {string} relationships.similarArtists.links.self
 * @property {object} relationships.trackProviders
 * @property {object} relationships.trackProviders.links
 * @property {string} relationships.trackProviders.links.self
 * @property {object} relationships.radio
 * @property {object} relationships.radio.links
 * @property {string} relationships.radio.links.self
 * @property {object} links
 * @property {string} links.self
 * @property {string} id
 * @property {string} type
 */

/** @typedef {object} Playlist
 * @property {object} data
 * @property {object} data.attributes
 * @property {string} data.attributes.name
 * @property {string} data.attributes.description
 * @property {boolean} data.attributes.bounded
 * @property {string} data.attributes.duration
 * @property {number} data.attributes.numberOfItems
 * @property {object[]} data.attributes.externalLinks
 * @property {string} data.attributes.externalLinks.href
 * @property {object} data.attributes.externalLinks.meta
 * @property {string} data.attributes.externalLinks.meta.type
 * @property {string} data.attributes.createdAt
 * @property {string} data.attributes.lastModifiedAt
 * @property {string} data.attributes.privacy
 * @property {string} data.attributes.playlistType
 * @property {object[]} data.attributes.imageLinks
 * @property {string} data.attributes.imageLinks.href
 * @property {object} data.attributes.imageLinks.meta
 * @property {number} data.attributes.imageLinks.meta.width
 * @property {number} data.attributes.imageLinks.meta.height
 * @property {object} data.relationships
 * @property {object} data.relationships.items
 * @property {object[]} data.relationships.items.data
 * @property {string} data.relationships.items.data.id
 * @property {string} data.relationships.items.data.type
 * @property {object} data.relationships.items.links
 * @property {string} data.relationships.items.links.self
 * @property {object} data.relationships.owners
 * @property {object} data.relationships.owners.links
 * @property {string} data.relationships.owners.links.self
 * @property {object} data.links
 * @property {string} data.links.self
 * @property {string} data.id
 * @property {string} data.type
 * @property {object[]} included
 * @property {object} included.attributes
 * @property {string} included.attributes.title
 * @property {string} included.attributes.isrc
 * @property {string} included.attributes.duration
 * @property {string} included.attributes.copyright
 * @property {boolean} included.attributes.explicit
 * @property {number} included.attributes.popularity
 * @property {string[]} included.attributes.availability
 * @property {string[]} included.attributes.mediaTags
 * @property {object[]} included.attributes.externalLinks
 * @property {string} included.attributes.externalLinks.href
 * @property {object} included.attributes.externalLinks.meta
 * @property {string} included.attributes.externalLinks.meta.type
 * @property {object} included.relationships
 * @property {object} included.relationships.albums
 * @property {object} included.relationships.albums.links
 * @property {string} included.relationships.albums.links.self
 * @property {object} included.relationships.artists
 * @property {object} included.relationships.artists.links
 * @property {string} included.relationships.artists.links.self
 * @property {object} included.relationships.providers
 * @property {object} included.relationships.providers.links
 * @property {string} included.relationships.providers.links.self
 * @property {object} included.relationships.similarTracks
 * @property {object} included.relationships.similarTracks.links
 * @property {string} included.relationships.similarTracks.links.self
 * @property {object} included.relationships.radio
 * @property {object} included.relationships.radio.links
 * @property {string} included.relationships.radio.links.self
 * @property {object} included.links
 * @property {string} included.links.self
 * @property {string} included.id
 * @property {string} included.type
 */

/** @typedef {object} TrackResponse
 * @property {object} data
 * @property {object} data.attributes
 * @property {string} data.attributes.title
 * @property {string} data.attributes.isrc
 * @property {string} data.attributes.duration
 * @property {string} data.attributes.copyright
 * @property {boolean} data.attributes.explicit
 * @property {number} data.attributes.popularity
 * @property {string[]} data.attributes.availability
 * @property {string[]} data.attributes.mediaTags
 * @property {object[]} data.attributes.externalLinks
 * @property {string} data.attributes.externalLinks.href
 * @property {object} data.attributes.externalLinks.meta
 * @property {string} data.attributes.externalLinks.meta.type
 * @property {object} data.relationships
 * @property {object} data.relationships.albums
 * @property {object[]} data.relationships.albums.data
 * @property {string} data.relationships.albums.data.id
 * @property {string} data.relationships.albums.data.type
 * @property {object} data.relationships.albums.links
 * @property {string} data.relationships.albums.links.self
 * @property {object} data.relationships.artists
 * @property {object[]} data.relationships.artists.data
 * @property {string} data.relationships.artists.data.id
 * @property {string} data.relationships.artists.data.type
 * @property {object} data.relationships.artists.links
 * @property {string} data.relationships.artists.links.self
 * @property {object} data.relationships.providers
 * @property {object} data.relationships.providers.links
 * @property {string} data.relationships.providers.links.self
 * @property {object} data.relationships.similarTracks
 * @property {object} data.relationships.similarTracks.links
 * @property {string} data.relationships.similarTracks.links.self
 * @property {object} data.relationships.radio
 * @property {object} data.relationships.radio.links
 * @property {string} data.relationships.radio.links.self
 * @property {object} data.links
 * @property {string} data.links.self
 * @property {string} data.id
 * @property {string} data.type
 * @property {object[]} included
 * @property {object} included.attributes
 * @property {string} included.attributes.name
 * @property {number} included.attributes.popularity
 * @property {object[]} included.attributes.imageLinks
 * @property {string} included.attributes.imageLinks.href
 * @property {object} included.attributes.imageLinks.meta
 * @property {number} included.attributes.imageLinks.meta.width
 * @property {number} included.attributes.imageLinks.meta.height
 * @property {object[]} included.attributes.externalLinks
 * @property {string} included.attributes.externalLinks.href
 * @property {object} included.attributes.externalLinks.meta
 * @property {string} included.attributes.externalLinks.meta.type
 * @property {object} included.relationships
 * @property {object} included.relationships.albums
 * @property {object} included.relationships.albums.links
 * @property {string} included.relationships.albums.links.self
 * @property {object} included.relationships.tracks
 * @property {object} included.relationships.tracks.links
 * @property {string} included.relationships.tracks.links.self
 * @property {object} included.relationships.videos
 * @property {object} included.relationships.videos.links
 * @property {string} included.relationships.videos.links.self
 * @property {object} included.relationships.similarArtists
 * @property {object} included.relationships.similarArtists.links
 * @property {string} included.relationships.similarArtists.links.self
 * @property {object} included.relationships.trackProviders
 * @property {object} included.relationships.trackProviders.links
 * @property {string} included.relationships.trackProviders.links.self
 * @property {object} included.relationships.radio
 * @property {object} included.relationships.radio.links
 * @property {string} included.relationships.radio.links.self
 * @property {object} included.links
 * @property {string} included.links.self
 * @property {string} included.id
 * @property {string} included.type
 * @property {string} included.attributes.title
 * @property {string} included.attributes.barcodeId
 * @property {number} included.attributes.numberOfVolumes
 * @property {number} included.attributes.numberOfItems
 * @property {string} included.attributes.duration
 * @property {boolean} included.attributes.explicit
 * @property {string} included.attributes.releaseDate
 * @property {string} included.attributes.copyright
 * @property {string[]} included.attributes.availability
 * @property {string[]} included.attributes.mediaTags
 * @property {Array<unknown>} included.attributes.videoLinks
 * @property {object} included.relationships.artists
 * @property {object} included.relationships.artists.links
 * @property {string} included.relationships.artists.links.self
 * @property {object} included.relationships.items
 * @property {object} included.relationships.items.links
 * @property {string} included.relationships.items.links.self
 * @property {object} included.relationships.similarAlbums
 * @property {object} included.relationships.similarAlbums.links
 * @property {string} included.relationships.similarAlbums.links.self
 * @property {object} included.relationships.providers
 * @property {object} included.relationships.providers.links
 * @property {string} included.relationships.providers.links.self
 */